package com.xxx.ency.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xxx.ency.model.bean.LikeBean;

import com.xxx.ency.model.db.LikeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeBeanDaoConfig;

    private final LikeBeanDao likeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);

        registerDao(LikeBean.class, likeBeanDao);
    }
    
    public void clear() {
        likeBeanDaoConfig.clearIdentityScope();
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

}
